---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp Keystone STaaS 서비스의 모든 릴리스에서 새롭고 향상된 기능을 제공합니다. 
---
= Keystone STaaS의 새로운 소식
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystone STaaS 서비스의 최신 기능과 향상된 기능에 대해 알아보세요.



== 2025년 12월 8일

NetApp Console 의 Keystone 대시보드의 새로운 기능 향상:



=== 누적 버스트 용량 레이블 이름이 변경되었습니다.

*누적 버스트 용량* 라벨이 *누적 버스트*로 이름이 변경되었습니다.



== 2025년 11월 24일

NetApp Console 의 Keystone 대시보드의 새로운 기능 향상:



=== 커버리지 갭 구독에 대한 추적 ID

*모니터링 > 알림 모니터*의 *보장 범위 완료* 알림 상자에서 각 구독의 구독 번호 옆에 추적 ID가 표시됩니다.



== 2025년 11월 10일

NetApp Console 의 Keystone 대시보드의 새로운 기능 향상:



=== 보장 알림 상자를 완성하세요

*모니터링* 페이지의 *알림 모니터* 탭에는 적용 범위에 차이가 있을 때 나타나는 *적용 범위 완료* 알림 상자가 포함되어 있습니다. 이 상자에는 용량 또는 만료 모니터가 없는 구독과 구독이 없는 모니터가 나열됩니다. 기존 모니터에 구독을 추가하거나, 새로운 모니터를 만들거나, 사용하지 않는 모니터를 삭제하여 격차를 해소할 수 있습니다. 자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html#manage-coverage-gaps["경보 모니터의 적용 범위 격차 관리"].



== 2025년 10월 13일

NetApp Console 의 Keystone 대시보드의 새로운 기능 향상:



=== 자산 탭의 QoS 정책 재정의 열

이제 *자산* 탭 내의 *클러스터의 볼륨* 탭에 백업 및 미러 볼륨에 대한 QoS 규칙을 우회할지 여부를 나타내는 *QoS 정책 재정의* 열이 포함되어 *true*(규칙 무시), *false*(규칙 적용) 또는 *N/A*(미러 볼륨)로 표시됩니다.


NOTE: Keystone v3 구독의 경우, v3 제품에는 QoS 정책이 적용되지 않으므로 이 열에는 *해당 없음*이 표시됩니다.



=== 개요 페이지에서 알림 가시성 향상

*개요* 페이지에는 이제 *심각도별 해결되지 않은 알림*과 *가장 오래된 해결되지 않은 Keystone 알림*이라는 두 개의 새로운 알림 섹션이 포함되었습니다. 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-console.html["NetApp 콘솔의 Keystone 대시보드"] .



== 2025년 10월 6일



=== BlueXP 는 이제 NetApp 콘솔입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp 콘솔은 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지와 NetApp 데이터 서비스를 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 내용에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp 콘솔 릴리스 노트"^] .



== 2025년 9월 22일



=== 알람 모니터링 추가

BlueXP 의 Keystone 대시보드에는 이제 구독 전반의 알림과 모니터를 관리하기 위한 *모니터링* 탭이 포함되었습니다. 이 새로운 탭을 사용하면 다음 작업을 수행할 수 있습니다.

* 시스템 생성 알림과 사용자 정의 알림(용량 사용 및 구독 만료)을 포함한 활성 알림을 보고 해결합니다.
* 용량 사용 및 구독 만료 이벤트를 추적하기 위해 알림 모니터를 만듭니다.


자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/keystone-staas-2/integrations/monitoring-alerts.html["알림 및 모니터 보기 및 관리"] .



=== 간소화된 성능 서비스 수준 보기

*구독* 탭에서 별도 탭에서 확장 가능한 보기로 이동된 성능 서비스 수준 정보를 볼 수 있습니다. 각 구독에 대한 만료일을 보려면 *만료일* 열 옆에 있는 아래쪽 화살표를 클릭하세요. 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/keystone-staas-2/integrations/subscriptions-tab.html["Keystone 구독에 대한 세부 정보 보기"] .



== 2025년 8월 28일



=== 새로운 열을 통해 향상된 논리적 사용 추적

FabricPool 볼륨에 대한 Keystone 소비량 추적을 강화하기 위해 새로운 열인 '전체 발자국'이 추가되었습니다.

* * BlueXP 의 Keystone 대시보드 *: *자산* 탭의 *클러스터 볼륨* 탭에서 *총 설치 공간* 열을 볼 수 있습니다.
* * Digital Advisor*: *볼륨 및 개체* 탭의 *볼륨 세부 정보* 탭에서 *총 공간* 열을 볼 수 있습니다.


이 열은 성능 및 콜드 계층의 데이터를 포함하여 FabricPool 계층화를 사용하는 볼륨의 총 논리적 설치 공간을 표시하므로 Keystone 소비량을 정확하게 계산할 수 있습니다.



== 2025년 8월 5일



=== 인스턴스 수준 소비 데이터 보기

BlueXP 의 Keystone 대시보드를 통해 각 성능 서비스 수준 인스턴스의 현재 소비량과 과거 데이터를 볼 수 있습니다.  이 기능은 Keystone 버전 3(v3) 구독이 있는 경우 여러 인스턴스가 있는 성능 서비스 수준에서 사용할 수 있습니다.  자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/keystone-staas/integrations/current-usage-tab.html["Keystone 구독 사용량 보기"] .



== 2025년 6월 30일



=== Keystone 버전 3(v3) 릴리스

이제 NetApp Keystone STaaS 제품의 최신 릴리스인 Keystone 버전 3(v3)을 구독할 수 있습니다.  이 버전에서는 간소화된 성능 서비스 수준, 추가 버스트 용량 옵션, 유연한 청구 빈도 등 여러 가지 향상된 기능이 도입되었습니다.  이러한 개선 사항을 통해 스토리지 솔루션의 관리, 최적화 및 확장이 간소화됩니다.  자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/keystone-staas/concepts/metrics.html["v3용 Keystone STaaS 서비스"] .

Keystone 버전 3(v3)을 구독하려면 Keystone 지원팀에 문의하세요. 자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/keystone-staas/concepts/support-services.html["Keystone 에 대한 도움말 받기"].



== 2025년 6월 19일



=== BlueXP 의 Keystone 대시보드

이제 BlueXP 에서 바로 Keystone 대시보드에 액세스할 수 있습니다.  이 통합을 통해 다른 NetApp 서비스와 함께 모든 Keystone 구독을 모니터링, 관리, 추적할 수 있는 단일 장소가 제공됩니다.

BlueXP 의 Keystone 대시보드를 사용하면 다음을 수행할 수 있습니다.

* 모든 구독 세부 정보, 용량 사용량 및 자산을 한 곳에서 확인하세요.
* 필요에 따라 구독을 쉽게 관리하고 변경을 요청하세요.
* 귀하의 스토리지 환경에 대한 최신 정보를 받아보세요.


시작하려면 BlueXP 왼쪽 탐색 메뉴에서 *저장소 > Keystone *으로 이동하세요.  자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/keystone-staas/integrations/dashboard-overview.html["Keystone 대시보드 개요"] .



== 2025년 1월 8일



=== 매일 누적된 데이터 사용량 보기 옵션 추가

청구된 데이터가 표시되는 막대를 클릭하면 월별 또는 분기별 청구 기간 동안 발생한 일일 버스트 데이터 사용량을 그래프 또는 표 형식으로 볼 수 있습니다.  자세한 내용은 다음을 참조하세요.link:./integrations/consumption-tab.html#view-daily-accrued-burst-data-usage["매일 누적된 버스트 데이터 사용량 보기"] .



== 2024년 12월 12일



=== 이름이 변경된 논리적 사용 열

*볼륨 및 개체* 내의 *볼륨 세부 정보* 탭에 있는 *논리적 사용* 열의 이름이 이제 * Keystone 논리적 사용*으로 변경되었습니다.



=== 향상된 자산 탭

* Keystone 구독* 화면의 *자산* 탭에 이제 두 개의 새로운 하위 탭, * ONTAP* 및 * StorageGRID*가 추가되었습니다.  이러한 하위 탭은 구독을 기반으로 ONTAP 대한 자세한 클러스터 수준 통찰력과 StorageGRID 에 대한 그리드 수준 정보를 제공합니다.  자세한 내용은 다음을 참조하세요.link:./integrations/assets-tab.html["자산 탭"^] .



=== 새로운 열 숨기기/표시 옵션

이제 *볼륨 및 개체* 내의 *볼륨 세부 정보* 탭에 *열 숨기기/표시* 옵션이 포함되었습니다.  이 옵션을 사용하면 사용자의 선호도에 따라 볼륨의 표 목록을 사용자 정의하기 위해 열을 선택하거나 선택 취소할 수 있습니다.  자세한 내용은 다음을 참조하세요.link:./integrations/volumes-objects-tab.html["볼륨 및 객체 탭"^] .



== 2024년 11월 21일



=== 향상된 청구 발생 버스트

분기별 청구 기간을 선택한 경우, 이제 *청구된 누적 버스트* 옵션을 통해 분기별로 누적 버스트 사용 데이터를 볼 수 있습니다.  자세한 내용은 다음을 참조하세요.link:./integrations/consumption-tab.html#view-accrued-burst["청구된 누적 버스트 보기"^] .



=== 볼륨 세부 정보 탭의 새 열

논리적 사용량을 계산할 때 명확성을 높이기 위해 *볼륨 및 개체* 탭 내의 *볼륨 세부 정보* 탭에 두 개의 새 열이 추가되었습니다.

* *논리적 AFS*: 볼륨의 활성 파일 시스템에서 사용하는 논리적 용량을 표시합니다.
* *물리적 스냅샷*: 스냅샷이 사용하는 물리적 공간을 표시합니다.


이러한 열은 볼륨의 활성 파일 시스템에서 사용하는 논리적 용량과 스냅샷에서 사용하는 물리적 공간을 합친 것을 보여주는 *논리적 사용* 열에 대한 명확성을 더 높여줍니다.



== 2024년 11월 11일



=== 향상된 보고서 생성

이제 Digital Advisor 의 보고서 기능을 사용하여 Keystone 데이터의 세부 정보를 볼 수 있는 통합 보고서를 생성할 수 있습니다.  자세한 내용은 다음을 참조하세요.link:./integrations/options.html#generate-consolidated-report-from-digital-advisor["통합 보고서 생성"^] .



== 2024년 7월 10일



=== 라벨 수정

*현재 사용량* 라벨이 *현재 소비량*으로 변경되고, *용량 추세* 라벨이 *소비량 추세*로 변경됩니다.



=== 구독 검색창

* Keystone 구독* 화면의 모든 탭에 있는 *구독* 드롭다운에 이제 검색 창이 포함되었습니다.  *구독* 드롭다운에 나열된 특정 구독을 검색할 수 있습니다.



== 2024년 6월 27일



=== 구독의 일관된 표시

* Keystone 구독* 화면이 업데이트되어 모든 탭에 선택한 구독 번호가 표시됩니다.

* * Keystone 구독* 화면 내의 탭을 새로 고치면 화면이 자동으로 *구독* 탭으로 이동하고 모든 탭이 *구독* 드롭다운에 나열된 첫 번째 구독으로 재설정됩니다.
* 선택한 구독이 성과 지표에 가입되어 있지 않으면, 탐색 시 *성과* 탭에 *구독* 드롭다운에 나열된 첫 번째 구독이 표시됩니다.




== 2024년 5월 29일



=== 향상된 버스트 표시기

사용량 그래프 인덱스의 *버스트* 표시기가 향상되어 버스트 한도 백분율 값을 표시합니다.  이 값은 구독에 대해 합의된 버스트 한도에 따라 달라집니다.  *사용 상태* 열의 *버스트 사용량* 표시기 위에 마우스를 올려놓으면 *구독* 탭에서 버스트 한도 값을 볼 수도 있습니다.



=== 서비스 수준 추가

*CVO Primary* 및 *CVO Secondary* 서비스 수준은 커밋된 용량이 없는 요금제를 사용하거나 메트로 클러스터로 구성된 구독에 대해 Cloud Volumes ONTAP 지원하기 위해 포함되었습니다.

* 이러한 서비스 수준에 대한 용량 사용 그래프는 * Keystone 구독* 위젯의 기존 대시보드와 *용량 추세* 탭에서 볼 수 있으며, *현재 사용* 탭에서 자세한 사용 정보도 볼 수 있습니다.
* *구독* 탭에서 이러한 서비스 수준은 다음과 같이 표시됩니다. `CVO (v2)` *사용 유형* 열에서 이러한 서비스 수준에 따른 청구를 식별할 수 있습니다.




=== 단기간 버스트를 위한 확대 기능

*용량 추세* 탭에는 이제 사용량 차트에서 단기 버스트의 세부 정보를 볼 수 있는 확대 기능이 포함되었습니다. 자세한 내용은 다음을 참조하세요. link:./integrations/consumption-tab.html["용량 추세 탭"^] .



=== 구독의 향상된 표시

구독의 기본 표시가 추적 ID별로 정렬되도록 향상되었습니다.  *구독* 탭의 구독, *구독* 드롭다운 및 CSV 보고서는 이제 추적 ID의 알파벳 순서에 따라 a, A, b, B 등의 순서로 표시됩니다.



=== 향상된 누적 버스트 표시

*용량 추세* 탭의 용량 사용량 막대 차트 위에 마우스를 올리면 나타나는 툴팁에 이제 커밋된 용량을 기준으로 발생한 버스트 유형이 표시됩니다.  임시 누적 버스트와 청구된 누적 버스트를 구분하여, 약정 용량이 0인 요금제가 있는 구독의 경우 *임시 누적 소비량*과 *청구된 누적 소비량*을 표시하고, 약정 용량이 0이 아닌 구독의 경우 *임시 누적 버스트*와 *청구된 누적 버스트*를 표시합니다.



== 2024년 5월 9일



=== CSV 보고서의 새 열

*용량 추세* 탭의 CSV 보고서에 이제 *구독 번호* 및 *계정 이름* 열이 포함되어 세부 정보가 더욱 향상되었습니다.



=== 향상된 사용 유형 열

*구독* 탭의 *사용 유형* 열이 개선되어 파일과 개체 모두에 대한 서비스 수준을 포함하는 구독에 대해 논리적 및 물리적 사용을 쉼표로 구분된 값으로 표시합니다.



=== 볼륨 세부 정보 탭에서 개체 스토리지 세부 정보에 액세스합니다.

*볼륨 및 개체* 탭 내의 *볼륨 세부 정보* 탭은 이제 파일과 개체 모두에 대한 서비스 수준을 포함하는 구독의 볼륨 정보와 함께 개체 저장소 세부 정보를 제공합니다.  *볼륨 세부 정보* 탭 내의 *개체 스토리지 세부 정보* 버튼을 클릭하면 세부 정보를 볼 수 있습니다.



== 2024년 3월 28일



=== 볼륨 세부 정보 탭의 QoS 정책 준수 표시 개선

이제 *볼륨 및 개체* 탭 내의 *볼륨 세부 정보* 탭에서 서비스 품질(QoS) 정책 준수에 대한 가시성이 향상되었습니다.  이전에 *AQoS*로 알려졌던 열의 이름이 *준수*로 바뀌었습니다. 이는 QoS 정책이 준수되는지 여부를 나타냅니다.  또한, 정책이 고정인지 적응형인지 지정하는 새로운 열인 *QoS 정책 유형*이 추가되었습니다.  두 가지 모두 해당되지 않으면 열에 _사용 불가_가 표시됩니다. 자세한 내용은 다음을 참조하세요. link:./integrations/volumes-objects-tab.html["볼륨 및 객체 탭"^] .



=== 볼륨 요약 탭에 새로운 열과 간소화된 구독 표시가 추가되었습니다.

* 이제 *볼륨 및 개체* 탭 내의 *볼륨 요약* 탭에 *보호됨*이라는 새 열이 포함되었습니다.  이 열은 귀하가 구독한 서비스 수준과 연관된 보호 볼륨의 수를 제공합니다.  보호된 볼륨의 수를 클릭하면 *볼륨 세부 정보* 탭으로 이동하며, 여기서 보호된 볼륨의 필터링된 목록을 볼 수 있습니다.
* *볼륨 요약* 탭이 업데이트되어 추가 서비스를 제외한 기본 구독만 표시됩니다. 자세한 내용은 다음을 참조하세요. link:./integrations/volumes-objects-tab.html["볼륨 및 객체 탭"^] .




=== 용량 추세 탭에서 누적 버스트 세부 정보 표시 변경

*용량 추세* 탭의 용량 사용량 막대 차트 위에 마우스를 올리면 나타나는 툴팁에는 현재 월에 발생한 버스트의 세부 정보가 표시됩니다.  지난 달에 대한 세부 정보는 제공되지 않습니다.



=== Keystone 구독에 대한 과거 데이터를 볼 수 있는 향상된 액세스

이제 Keystone 구독이 수정되거나 갱신되면 이전 데이터를 볼 수 있습니다.  구독 시작 날짜를 이전 날짜로 설정하여 다음을 확인할 수 있습니다.

* *용량 추세* 탭에서 소비량 및 누적 버스트 사용 데이터를 확인할 수 있습니다.
* *성능* 탭에서 ONTAP 볼륨의 성능 측정 항목을 볼 수 있습니다.


데이터는 선택한 구독 시작 날짜를 기준으로 표시됩니다.



== 2024년 2월 29일



=== 자산 탭 추가

* Keystone 구독* 화면에 이제 *자산* 탭이 포함되었습니다.  이 새로운 탭은 귀하의 구독을 기반으로 클러스터 수준 정보를 제공합니다. 자세한 내용은 다음을 참조하세요. link:./integrations/assets-tab.html["자산 탭"^] .



=== 볼륨 및 개체 탭 개선

ONTAP 시스템 볼륨에 대한 명확성을 높이기 위해 *볼륨 요약* 및 *볼륨 세부 정보*라는 두 개의 새 탭 버튼이 *볼륨* 탭에 추가되었습니다.  *볼륨 요약* 탭은 구독한 서비스 수준과 연관된 볼륨의 전체 수를 제공하며, 여기에는 AQoS 준수 상태와 용량 정보가 포함됩니다.  *볼륨 세부 정보* 탭에는 모든 볼륨과 해당 세부 정보가 나열됩니다. 자세한 내용은 다음을 참조하세요. link:./integrations/volumes-objects-tab.html["볼륨 및 객체 탭"^] .



=== Digital Advisor 의 향상된 검색 경험

* Digital Advisor* 화면의 검색 매개변수에는 이제 Keystone 구독 번호와 Keystone 구독을 위해 생성된 관심 목록이 포함됩니다.  구독 번호 또는 관심 목록 이름의 처음 세 글자를 입력할 수 있습니다. 자세한 내용은 다음을 참조하세요. link:./integrations/keystone-aiq.html["Active IQ Digital Advisor 에서 Keystone 대시보드 보기"^] .



=== 소비 데이터의 타임스탬프 보기

* Keystone Subscriptions* 위젯의 이전 대시보드에서 소비 데이터의 타임스탬프(UTC)를 볼 수 있습니다.



== 2024년 2월 13일



=== 기본 구독에 연결된 구독을 볼 수 있는 기능

일부 기본 구독에는 연결된 보조 구독이 있을 수 있습니다.  이 경우 기본 구독 번호는 계속 *구독 번호* 열에 표시되고, 연결된 구독 번호는 *구독* 탭의 새 열인 *연결된 구독*에 나열됩니다.  *연계된 구독* 열은 연계된 구독이 있는 경우에만 사용할 수 있으며, 이를 알리는 정보 메시지를 볼 수 있습니다.



== 2024년 1월 11일



=== 발생한 버스트에 대해 청구된 데이터가 반환되었습니다.

*적립된 버스트*에 대한 라벨은 이제 *용량 추세* 탭에서 *청구된 적립 버스트*로 수정되었습니다.  이 옵션을 선택하면 청구된 누적 버스트 데이터에 대한 월별 차트를 볼 수 있습니다. 자세한 내용은 다음을 참조하세요. link:./integrations/consumption-tab.html#view-accrued-burst["청구된 누적 버스트 보기"^] .



=== 특정 요금제에 대한 누적 소비 세부 정보

약정 용량이 _0_인 요금제가 포함된 구독이 있는 경우, *용량 추세* 탭에서 누적된 소비 세부 정보를 볼 수 있습니다.  *청구된 누적 소비량* 옵션을 선택하면 청구된 누적 소비량 데이터에 대한 월별 차트를 볼 수 있습니다.



== 2023년 12월 15일



=== 관심목록으로 검색하는 기능

Digital Advisor 의 관심 목록에 대한 지원이 Keystone 시스템을 포함하도록 확장되었습니다.  이제 관심목록으로 검색하여 여러 고객의 구독 세부 정보를 볼 수 있습니다.  Keystone STaaS에서 감시 목록 사용에 대한 자세한 내용은 다음을 참조하세요.link:./integrations/keystone-aiq.html#search-by-keystone-watchlists["Keystone 관심 목록으로 검색"^] .



=== UTC 시간대로 변환된 날짜

Digital Advisor 의 * Keystone 구독* 화면 탭에 반환된 데이터는 UTC 시간(서버 시간대)으로 표시됩니다.  쿼리를 위해 날짜를 입력하면 자동으로 UTC 시간으로 간주됩니다. 자세한 내용은 다음을 참조하세요. link:./integrations/keystone-aiq.html["Keystone 구독 대시보드 및 보고"^] .
