---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v2, version 2 
summary: NetApp Keystone STaaS 서비스는 여러 가지 용어를 사용하여 지표를 측정합니다.  Keystone 서비스 버전 2를 사용할 때 이러한 약관에 대해 자세히 알아보는 것이 좋습니다. 
---
= Keystone 에서 사용되는 측정항목 및 정의
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 서비스는 여러 가지 용어를 사용하여 지표를 측정합니다.  Keystone 사용하면서 이러한 용어에 대해 자세히 알아보는 것이 좋습니다.

다음 용어와 정의는 Keystone STaaS 서비스 내에서 지표를 측정하는 데 사용됩니다.

* 용량: GiB, TiB, PiB로 측정됩니다.
* IO 밀도: IOPS/TiB: 워크로드에서 사용되는 총 공간을 기준으로 초당 처리되는 입출력 작업 수(테라바이트)입니다.
* 서비스 가용성
* 정확한 데이터 접근의 내구성
* 지연 시간과 속도




== 지표 측정

* *GiB, TiB, PiB 단위의 용량 측정*: 1024를 기준으로 데이터 저장 용량을 측정합니다(1GiB = 1024^3^바이트, 1TiB = 1024^4^바이트, 1PiB = 1024^5^바이트).
* *IOPS/TiB 단위의 작업 카운터 차트*: 애플리케이션에서 요청한 초당 프로토콜 작업을 워크로드에서 사용하는 볼륨 크기로 나눈 값입니다.
* *가용성*: 서비스가 성공적으로 응답한 I/O 요청 수를 서비스에 대한 총 I/O 요청 수로 나눈 백분율로 측정합니다.  이는 한 달 동안의 서비스 경계에서 측정되며, 예정된 서비스 중단 시간이나 고객이 제공한 시설, 네트워크 또는 기타 서비스의 이용 불가는 포함되지 않습니다.
* *내구성*: 고객으로 인한 삭제 또는 손상을 제외하고, 데이터 충실도 손실 없이 액세스한 데이터의 백분율입니다.
* *지연 시간*: 클라이언트로부터 수신된 I/O 요청을 처리하는 데 걸리는 시간으로, 서비스 경계(스토리지 컨트롤러 I/O 포트)에서 측정됩니다.




=== 처리량 성능 지표

처리량 성능 측정항목은 다음을 기준으로 파일 및 블록 서비스에만 적용됩니다.

* 32KB 블록 크기
* 70% 읽기/30% 쓰기 I/O 혼합




=== IO 밀도의 변화

IOPS/TiB 및/또는 MBps/TiB로 계산된 IO 밀도는 다음 요소에 따라 달라집니다.

* 작업 부하 특성
* 다음을 제외한 지연 시간:
+
** 애플리케이션 지연 시간
** 호스트 대기 시간
** 컨트롤러 포트에서 데이터를 전송하는 동안 고객 네트워크에서 지연이 발생합니다.
** FabricPool 의 경우 객체 저장소로의 데이터 전송과 관련된 오버헤드 대기 시간
** IO를 서비스 수준 최대치 내로 유지하기 위해 QoS에서 자동으로 적용하는 대기 시간


* 사용자 및 스냅샷은 사용된 용량의 일부로 계산되는 데이터를 복사합니다.
* 볼륨의 데이터 양에 관계없이 각 ONTAP 볼륨에 할당된 절대 최소 IOPS:
+
** 극한: 1,000 IOPS
** 프리미엄: 500 IOPS
** 성능, 표준 및 가치: 75 IOPS


* Advanced Data Protection 추가 서비스를 사용하는 동안 대상 지연 시간은 로컬 스토리지에서 IO 요청을 처리하는 데에만 적용됩니다.




=== 볼륨 AQoS

각 ONTAP 볼륨에는 적용 가능한 적응형 서비스 품질(AQoS) 정책이 적용되어야 합니다.  그렇지 않은 경우 AQoS 정책이 적용되지 않은 각 볼륨 내의 용량은 가장 높은 서비스 수준의 요금으로 청구됩니다.
