---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: 복제된 볼륨, 고급 데이터 보호 등 특정 구성에 대한 Keystone 청구에 대해 알아보세요. 
---
= Keystone 청구에 대한 다양한 시나리오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
특정 구성에 대한 Keystone 청구를 이해하면 서비스 사용을 최적화하고 비용을 관리하는 데 도움이 될 수 있습니다.  구성에는 복제된 볼륨, 고급 데이터 보호, 임시 볼륨, QoS 정책, SnapMirror 대상, LUN 및 시스템/루트 볼륨이 포함됩니다.



== 복제된 볼륨에 대한 청구

ONTAP 에서 볼륨을 복제하고 이를 사용하여 데이터를 백업하고 복원하는 경우 추가 비용 없이 복제본을 계속 사용할 수 있습니다.  그러나 장기간에 걸쳐 사업상의 다른 목적으로 사용된 복제 볼륨에는 요금이 부과됩니다.

다음 사항에 유의하세요.

* 복제 볼륨의 크기가 부모 볼륨의 10% 미만인 경우 요금이 부과되지 않습니다(부모 볼륨에서 사용된 물리적 용량과 복제 볼륨에서 사용된 물리적 용량을 비교한 값).
* 복제된 볼륨에는 24시간의 유예 기간이 없습니다.  클론의 크기만 고려됩니다.
* 복제 볼륨이 부모의 물리적 크기의 10%를 초과하면 복제 볼륨은 표준 볼륨(논리적 사용 용량)으로 청구됩니다.




== 고급 데이터 보호에 대한 청구

고급 데이터 보호 기능은 NetApp MetroCluster 사용하여 두 개의 물리적으로 분리된 클러스터 간에 데이터를 미러링합니다.  MetroCluster 미러링 집계의 경우 데이터는 각 클러스터에 한 번씩, 총 두 번 기록됩니다.  Keystone 서비스는 각 측의 소비량에 대해 독립적으로 요금을 부과하므로 두 개의 동일한 소비 기록이 생성됩니다.  추가 요금은 데이터가 소스에 있는지, 미러링되었는지, 미러링되지 않았는지에 관계없이 구독의 모든 용량에 적용됩니다.

각 MetroCluster 사이트에는 자체 구독 및 청구 시스템이 있습니다.  MetroCluster 구성의 경우 사용량 측정은 두 사이트에서 저장소가 어떻게 활용되는지를 설명합니다.  사이트당 100TiB의 MetroCluster 설정한 경우 각 사이트에서 실제로 사용되는 것은 50TiB뿐이며, 각 사이트의 나머지 50TiB는 미러링된 백업으로 사용됩니다.  고급 데이터 보호 추가 요금제는 총 활성 사용량 100TiB를 기준으로 계산되며, 각 사이트의 구독을 통해 각각 50TiB씩 분할됩니다.

ONTAP System Manager(시스템 관리자) 또는 Active IQ Unified Manager (통합 관리자)를 통해 클러스터를 모니터링하는 경우 이러한 도구와 Keystone 에서 보고된 사용량 사이에 불일치가 나타날 수 있습니다.  System Manager와 Unified Manager는 미러링된(원격) 클러스터의 볼륨을 보고하지 않으며, 그렇게 함으로써 Keystone 서비스가 보고하는 소비 메트릭의 절반만 보고합니다.

.예:
사이트 A와 사이트 B는 MetroCluster 구성으로 설정됩니다. 사용자가 사이트 A에 10TB 볼륨을 생성하면 사이트 B에도 동일한 10TB 볼륨이 생성됩니다. Keystone 각 사이트에서 10TB의 사용량을 식별하여 총 20TB가 증가했습니다. 시스템 관리자와 통합 관리자는 사이트 A에 10TB 볼륨이 생성되었다고 보고하지만, 사이트 B에는 10TB 볼륨이 생성되었다고 보고하지 않습니다.

또한, 고급 데이터 보호 기능이 있는 Keystone 시스템에서 생성된 모든 볼륨은 해당 볼륨이 미러링되었는지 여부와 관계없이 고급 데이터 보호 사용량에 포함됩니다.



== 임시 볼륨에 대한 청구

가끔 ONTAP 에서 볼륨을 이동할 때 임시(TMP) 볼륨이 생성됩니다.  이러한 일시적인 볼륨은 지속 시간이 짧으며, 이러한 볼륨의 소비량은 청구 시 측정되지 않습니다.



== 청구 및 적응형 QoS 정책

Keystone 서비스 수준에 따라 소비량을 측정합니다.  각 서비스 수준은 특정 적응형 서비스 품질(QoS) 정책과 연관됩니다.  배포하는 동안 귀하가 구독한 Keystone 서비스에 대한 각 적응형 QoS 정책의 세부 정보가 안내됩니다.  저장소 관리 작업 중에 구독한 서비스 수준에 따라 볼륨에 적절한 적응형 QoS 정책이 할당되어 있는지 확인하여 예상치 못한 청구가 발생하지 않도록 하세요.  ONTAP 의 적응형 QoS 정책에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS 개요를 통한 처리량 보장"^] .



== SnapMirror 대상에 대한 청구

SnapMirror 대상 볼륨의 가격은 소스에 할당된 서비스 수준에 대한 적응형 QoS 정책에 따라 결정됩니다.  그러나 소스에 연관된 적응형 QoS 정책이 없는 경우 대상은 사용 가능한 가장 낮은 서비스 수준을 기준으로 요금이 청구됩니다.



== LUN에 대한 청구

LUN의 경우 적응형 QoS 정책이 적용되는 볼륨과 동일한 청구 패턴이 적용됩니다.  LUN에 별도의 적응형 QoS 정책이 설정된 경우:

* LUN의 크기는 해당 LUN의 연관된 서비스 수준에 따라 소비되는 것으로 계산됩니다.
* 볼륨에 남은 공간이 있는 경우, 볼륨에 설정된 서비스 수준의 적응형 QoS 정책에 따라 요금이 청구됩니다.




== 시스템 및 루트 볼륨

시스템 및 루트 볼륨은 Keystone 서비스의 전반적인 모니터링의 일부로 모니터링되지만 계산되거나 요금이 청구되지 않습니다.  이러한 양의 소비는 청구 대상에서 제외됩니다.
