---
sidebar: sidebar 
permalink: concepts/nrnvc.html 
keywords: Non-returnable, non-volatile components, SnapLock compliance, add-on service 
summary: NetApp Keystone 구독의 일부로 NetApp 파일, 블록 및 개체 서비스에 대한 NRNVC 제공을 확장합니다. 
---
= Keystone) 용 반환 불가, 비휘발성 부품 및 SnapLock) 규정 준수 추가 서비스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone 구독의 일부로 NetApp 파일, 블록 및 개체 서비스에 대한 반품 불가, 비휘발성 구성 요소(NRNVC) 제공을 확장합니다.

NetApp 서비스 제공 기간 동안 사용된 물리적 저장 매체를 복구하지 않으며, NetApp 서비스 제공에 사용된 모든 물리적 자산을 복구한 경우 서비스 종료 시에도 해당 물리적 저장 매체를 복구하지 않습니다.

이 추가 서비스는 Keystone 구독의 일부로 구독할 수 있습니다.  이 서비스를 구매한 경우 다음 사항에 유의하세요.

* 서비스 기간이 끝난 후 또는 서비스 기간 중에 고장이 나거나 결함이 발견된 경우 드라이브나 비휘발성 메모리를 반환할 필요가 없습니다.
* 하지만 드라이브 및/또는 비휘발성 메모리에 대한 파기 인증서를 제출해야 하며 다른 용도로는 사용할 수 없습니다.
* NRNVC와 관련된 추가 비용은 총 구독 서비스(표준 서비스, 고급 데이터 보호, 데이터 계층화 포함) 월별 청구서의 백분율로 청구됩니다.
* 이 서비스는 파일, 블록, 개체 서비스에만 적용됩니다.


표준 및 클라우드 서비스에 대한 정보는 다음을 참조하세요.link:supported-storage-services.html["Keystone STaaS 서비스"] .

성과 서비스 수준에 대한 정보는 다음을 참조하세요.link:../concepts/service-levels.html["Keystone 의 성과 서비스 수준"] .



== SnapLock 준수

SnapLock 기술은 볼륨에 설정된 만료 날짜 이후에는 드라이브를 사용할 수 없게 만들어 NRNVC 기능을 활성화합니다.  볼륨에서 SnapLock 기술을 사용하려면 NRNVC에 가입해야 합니다.  이는 파일 및 블록 서비스에만 적용됩니다.

SnapLock 기술에 대한 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/snaplock/snaplock-concept.html["SnapLock 이란 무엇입니까?"^] .
