---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Keystone 스토리지 QoS를 사용하여 애플리케이션이 일관되고 예측 가능한 성능을 얻도록 보장합니다. 
---
= Keystone 의 스토리지 QoS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone 스토리지 서비스 품질(QoS)을 사용하여 애플리케이션이 일관되고 예측 가능한 성능을 얻도록 보장합니다.  QoS가 없으면 여러 시스템을 부팅하는 것과 같은 특정 작업 부하가 일정 시간 동안 대부분 또는 모든 리소스를 소모하여 다른 작업 부하에 영향을 미칠 수 있습니다.

QoS에 대한 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS 개요를 통한 처리량 보장"^] .



== 적응형 QoS

Keystone 서비스는 볼륨 크기에 따라 IOPS/TiB 비율을 동적으로 유지하기 위해 적응형 QoS(AQoS)를 사용합니다.  AQoS 정책에 대한 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["적응형 QoS에 대하여"^] .

Keystone 클러스터가 프로덕션에 들어간 후 설정할 수 있는 AQoS 정책을 제공합니다.  모든 볼륨이 이미 생성되어 시스템에서 사용 가능한 올바른 AQoS 정책과 연결되어 있는지 확인해야 합니다.

ONTAP 볼륨에 AQoS 정책이 적용되지 않으면 해당 볼륨은 규정을 준수하지 않는 것으로 간주됩니다.  QoS 정책이 없는 볼륨은 시스템이 사용 가능한 입출력 작업을 제공하는 데 있어 우선순위 목록의 마지막에 위치합니다.  그러나 입출력 작업이 가능한 경우 볼륨은 사용 가능한 모든 IO를 소모할 수 있습니다.


NOTE: 볼륨에 AQoS 정책을 적용하지 않은 경우 해당 볼륨은 귀하의 구독에 따라 가장 높은 서비스 수준으로 측정되고 요금이 청구됩니다.  이로 인해 의도치 않은 폭발이 발생할 수 있습니다.



== 적응형 QoS 설정

적응형 QoS(AQoS) 설정은 서비스 수준에 따라 달라집니다.

|===


| *정책명* | *극심한* | *프리미엄* | *성능* | *기준* | *값* 


| *예상 IOPS/TiB* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *예상 IOPS 할당* 5+| 할당된 공간 


| *피크 IOPS/TiB* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *피크 IOPS 할당* 5+| 사용된 공간 


| *블록 크기* 5+| 32K 
|===


== 적응형 QoS 정책 그룹 구성

적응형 QoS(AQoS) 정책을 구성하여 처리량 상한이나 최소 처리량 크기를 자동으로 조정할 수 있습니다.  모든 Keystone 서비스 수준이 기본 ONTAP QoS 정책과 일치하는 것은 아닙니다.  사용자 정의 QoS 정책을 만들 수 있습니다.  정책을 구성하려면 다음 사항을 알아야 합니다.

* *정책 그룹 이름*: AQoS 정책 그룹의 이름입니다. 예를 들어,  `Keystone_extreme` .
* *VServer*: VServer 또는 스토리지 VM(스토리지 가상 머신)의 이름입니다.
* *예상 IOPS/TiB*: 충분한 시스템 IOPS가 사용 가능할 때 시스템이 제공하려고 시도하는 볼륨당 할당된 TiB당 최소 IOPS 수입니다.
* *최대 IOPS/TiB*: 볼륨당 사용된 TiB당 최대 IOPS 수로, 시스템이 지연 주입을 통해 IOPS를 제한하기 전에 볼륨이 도달하도록 허용하는 수치입니다.
* *예상 IOPS 할당*: 이 매개변수는 볼륨에서 사용할 수 있는 예상 IOPS가 볼륨의 할당된 크기나 사용된 크기에 따라 결정되는지 여부를 제어합니다.  Keystone 에서는 할당된 공간을 기준으로 합니다.
* *최대 IOPS 할당*: 이 매개변수는 볼륨에서 사용할 수 있는 최대 IOPS가 볼륨의 할당된 크기나 사용된 크기에 따라 결정되는지 여부를 제어합니다.  Keystone 의 경우 이는 사용된 공간을 기준으로 합니다.
* *절대 최소 IOPS*: 볼륨 크기가 매우 작은 경우 볼륨에 적용될 것으로 예상되는 최소 IOPS 수치로, 그렇지 않으면 허용할 수 없는 수준의 IOPS가 발생합니다.  이 값은 기본적으로 1,000으로 설정됩니다. `Extreme` , 500개 `Premium` , 그리고 250개 `Performance` , 그리고 75개 `Standard` 그리고 `Value` 서비스 수준.
+

NOTE: 이는 IOPS 밀도(예: 75 IOPS/TiB)가 아니라, 절대 최소 IOPS 수입니다.



IO 밀도에 대한 정보는 다음을 참조하세요.link:../concepts/metrics.html["Keystone Services에서 사용되는 측정항목 및 정의"] .  AQoS 정책 그룹에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/performance-admin/adaptive-qos-policy-groups-task.html["적응형 QoS 정책 그룹 사용"^] .



== 적응형 QoS 정책 설정

다음 섹션에서는 각 서비스 수준에 대한 적응형 QoS(AQoS) 정책 설정을 설명합니다.  여기에 제공된 각 서비스 수준에 대한 최소 및 최대 볼륨 크기는 볼륨에 대한 최적의 IOP 및 지연 시간 값을 허용합니다.  이러한 지침에 맞지 않게 볼륨을 너무 많이 생성하면 해당 볼륨의 성능에 부정적인 영향을 미칠 수 있습니다.



=== Extreme 서비스 수준에 대한 설정

Extreme 서비스 수준에 대한 설정 및 명령:

* 샘플 명령:


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 1000
....
* 권장 최소 볼륨 크기: 100GiB, 0.1TiB
* 권장 최대 볼륨 크기: 10TiB




=== 프리미엄 서비스 수준 설정

프리미엄 서비스 수준에 대한 설정 및 명령:

* 샘플 명령:


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 500
....
* 권장 최소 볼륨 크기: 500GiB, 0.5TiB
* 권장 최대 볼륨 크기: 50TiB




=== 성능 서비스 수준 설정

성능 서비스 수준에 대한 설정 및 명령:

* 샘플 명령:


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 250
....
* 권장 최소 볼륨 크기: 500GiB, 0.5TiB
* 권장 최대 볼륨 크기: 80TiB




=== 표준 서비스 수준에 대한 설정

표준 서비스 수준에 대한 설정 및 명령:

* 샘플 명령:


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 권장 최소 볼륨 크기: 1TiB
* 권장 최대 볼륨 크기: 100TiB




=== 값 서비스 수준 설정

Value 서비스 수준에 대한 설정 및 명령:

* 샘플 명령:


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 권장 최소 볼륨 크기: 1TiB
* 권장 최대 볼륨 크기: 100TiB




== 블록 크기 계산

다음 설정을 사용하여 블록 크기를 계산하기 전에 다음 사항에 유의하세요.

* IOPS/TiB = MBps/TiB / (블록 크기 * 1024)
* 블록 크기는 KB/IO입니다.
* TiB = 1024GiB; GiB = 1024MiB; MiB = 1024KiB; KiB = 1024바이트; 기본 2에 따라
* TB = 1000GB; GB = 1000MB; MB = 1000KB; KB = 1000바이트; 10진법 기준


.샘플 블록 크기 계산
예를 들어 서비스 수준에 대한 처리량을 계산하려면 `Extreme` 서비스 수준:

* 최대 IOPS: 12,288
* I/O당 블록 크기: 32KB
* 최대 처리량 = (12288 * 32 * 1024) / (1024*1024) = 384MBps/TiB


볼륨에 700GiB의 논리적 사용 데이터가 있는 경우 사용 가능한 처리량은 다음과 같습니다.

`Maximum throughput = 384 * 0.7 = 268.8MBps`
