---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS는 사전 정의된 서비스 수준에서 저장 용량을 제공합니다.  Keystone 이 관리하는 각 볼륨은 서비스 수준과 연관됩니다. 
---
= Keystone 의 성능 서비스 수준
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS는 사전 정의된 성능 서비스 수준에서 데이터 저장 용량을 제공합니다.  Keystone 서비스에서 관리하는 각 볼륨은 성능 서비스 수준과 연관됩니다.

구독에는 여러 가지 요금제가 있을 수 있으며, 각 요금제는 성과 서비스 수준에 해당합니다.  각 요금제에는 성능 서비스 수준별로 약정된 용량이 있습니다.

각 성능 서비스 수준은 I/O 밀도, 즉 IOPS/TiB/볼륨으로 정의됩니다.  이는 성능(초당 입출력 작업 수[IOPS])과 사용된 저장 용량(TiB)의 비율로, 볼륨당 평균 지연 시간에서의 IOPS/TiB입니다.

스토리지 환경, 스토리지 및 소비 요구 사항에 따라 성능 서비스 수준을 선택합니다.  기본 성능 서비스 수준은 기본적으로 제공됩니다.  추가 서비스를 선택한 경우 구체적인 성과 서비스 수준도 추가로 이용할 수 있습니다.  예를 들어, 고급 데이터 보호 추가 서비스의 경우 _고급 데이터 보호_ 성능 서비스 수준이 귀하의 구독에 할당됩니다.


TIP: NetApp Keystone STaaS 성능 서비스 수준에 대한 자세한 서비스 설명을 사용할 수 있습니다. https://www.netapp.com/services/keystone/terms-and-conditions/["여기"^] .

지원되는 스토리지 유형, 파일, 블록, 개체 및 클라우드 서비스에 대한 기본 성능 서비스 수준은 다음 섹션에 설명되어 있습니다.



== 파일 및 블록 스토리지에 대한 성능 서비스 수준

*지원 프로토콜*: NFS, CIFS, iSCSI 및 FC

|===


| *성능 서비스 수준* | *극심한* | *프리미엄* | *성능* | *기준* | *값* 


| *샘플 작업 유형* | 분석, 데이터베이스, 미션 크리티컬 앱 | VDI, VSI, 소프트웨어 개발 | OLTP, OLAP, 컨테이너, 소프트웨어 개발 | 파일 공유, 웹 서버 | 지원 


| *볼륨당 저장된 최대 IOPS/논리적 TiB* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *볼륨당 할당된 최대 IOPS/논리적 TiB* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *볼륨당 저장된 최대 MBps/논리 TiB @ 32KB/S* | 384 | 128 | 64 | 16 | 4 


| *대상 90번째 백분위수 지연 시간* | <1밀리초 | <2밀리초 | <4밀리초 | <4밀리초 | <17밀리초 


| *블록 크기* 5+| 32K 


| *약정 및 측정 용량 유형* 5+| 논리적 
|===


=== 파일 및 블록 스토리지의 성능 서비스 수준에 대한 추가 정보

기본 성능 서비스 수준 측정항목은 다음 조건에 따라 달라집니다.

* 파일 및 블록 스토리지에 대한 성능 서비스 수준은 ONTAP 9.7 이상을 지원합니다.
* 성능 서비스 수준에 대한 IOPS/TiB/볼륨, MBps/TiB/볼륨 및 대기 시간 값은 볼륨에 저장된 데이터 양, 32KB 블록 크기 및 70% 읽기 및 30% 쓰기 IO 작업의 무작위 조합을 기반으로 합니다.
* 실제 IOPS/TiB/볼륨 및 MBps/TiB/볼륨은 실제 또는 가정 블록 크기, 시스템 작업 부하 동시성 또는 입출력 작업에 따라 달라질 수 있습니다.
* 지연 시간에는 다음 사항이 포함되지 않습니다.
+
** 애플리케이션 또는 호스트 지연 시간
** 컨트롤러 포트에서 또는 컨트롤러 포트로의 고객 네트워크 지연 시간
** FabricPool 의 경우 객체 저장소로의 데이터 전송과 관련된 오버헤드
** QoS에서 IO를 성능 서비스 수준 최대치 내로 유지하기 위해 자동으로 적용되는 대기 시간


* 대기 시간 값은 MetroCluster 쓰기 작업에 적용되지 않습니다.  이러한 쓰기 작업은 원격 시스템의 거리에 따라 달라집니다.
* 스토리지 시스템의 하나 이상의 볼륨에 AQoS 정책이 할당되지 않은 경우, 이러한 볼륨은 비준수 볼륨으로 간주되며, 해당 시스템에는 목표 성능 서비스 수준이 적용되지 않습니다.
* _예상 IOPS_는 계층화 정책이 "없음"으로 설정되고 클라우드에 블록이 없는 경우에만 FabricPool 을 대상으로 합니다.  _예상 IOPS_는 SnapMirror 동기 관계에 있지 않은 볼륨을 대상으로 합니다.
* 워크로드 IO 작업은 Keystone 순서에 따라 결정된 대로 배포된 모든 컨트롤러에서 균형을 이루어야 합니다.




== 객체 스토리지

*지원 프로토콜*: S3

|===


| *성능 서비스 수준* | 물체 


| *작업량 유형* | 미디어 저장소, 보관 


| *볼륨당 저장된 최대 IOPS/논리적 TiB* | 해당 없음 


| *볼륨당 저장되는 최대 MBps/논리 TiB* | 해당 없음 


| *평균 지연 시간* | 해당 없음 


| *약정 및 측정 용량 유형* | 물리적 
|===

NOTE: FabricPool 스토리지의 경우 개체 저장소로의 데이터 전송과 관련된 오버헤드는 대기 시간에 포함되지 않습니다.



== 클라우드 스토리지

*지원 프로토콜*: NFS, CIFS, iSCSI 및 S3(AWS 및 Azure만 해당)

|===


| *성능 서비스 수준* | Cloud Volumes ONTAP 


| *작업량 유형* | 재해 복구, 소프트웨어 개발/테스트, 비즈니스 앱 


| *볼륨당 저장된 최대 IOPS/논리적 TiB* | 해당 없음 


| *볼륨당 저장되는 최대 MBps/논리 TiB* | 해당 없음 


| *평균 지연 시간* | 해당 없음 
|===
[NOTE]
====
* 컴퓨팅, 스토리지, 네트워킹과 같은 클라우드 네이티브 서비스는 클라우드 제공업체에서 청구됩니다.
* 이러한 서비스는 클라우드 스토리지와 컴퓨팅 특성에 따라 달라집니다.


====
*관련 정보*

* link:../concepts/supported-storage-capacity.html["지원되는 저장 용량"]
* link:..//concepts/metrics.html["Keystone 서비스에서 사용되는 측정항목 및 정의"]
* link:../concepts/qos.html["Keystone 의 서비스 품질(QoS)"]
* link:../concepts/pricing.html["Keystone 가격"]

