---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: NetApp Keystone STaaS 서비스 버전 2에서 지원하는 스토리지 용량 유형에 대해 알아보세요. 
---
= Keystone 에서 지원되는 저장 용량
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 서비스는 여러 유형의 스토리지 용량을 지원합니다.  이러한 다양한 용량 용어를 이해하면 Keystone 사용할 때 도움이 될 수 있습니다.



[[logical-capacity]]
== 논리적 용량

이는 스토리지 어레이에서 제공하는 데이터 효율성이 적용되기 전에 사용자 데이터를 저장하는 데 필요한 스토리지 용량입니다.



[[committed-capacity]]
== 약속된 용량

구독 기간 동안 매달 청구되는 최소 논리적 용량:

* 각 성능 서비스 수준에 따라 용량이 결정됩니다.
* 계약 기간 중에 약속된 용량과 추가 서비스 수준을 추가할 수 있습니다.




[[changes-to-committed-capacity]]
=== 커밋된 용량 변경

구독 기간 동안 약정 용량을 변경할 수 있습니다.  하지만 다음과 같은 전제 조건이 있습니다.

* 특정 조건에 따라 약정된 용량을 줄일 수 있습니다.  자세한 내용은 다음을 참조하세요.link:../concepts/capacity-requirements.html["용량 감소"] .
* 구독을 추가로 12개월 기간으로 갱신하는 경우를 제외하고는 구독 만료일 90일 전부터는 약정 용량을 늘릴 수 없습니다.
* 콘솔이나 Keystone Success Manager(KSM)를 통해 약정된 용량에 대한 변경을 요청할 수 있습니다. 변경 요청에 대한 정보는 다음을 참조하세요. link:../concepts/support-services.html["NetApp Keystone 지원"].




[[consumed-capacity]]
== 소비 용량

사용 용량은 서비스에서 현재 사용 중인 용량(스토리지 TiB)을 나타냅니다. 데이터 스토리지 유형에 따라 계산 방식이 다릅니다.

* *통합형 또는 블록 최적화 스토리지*: 사용된 용량은 주문 과정에서 선택한 용량 유형(논리적 또는 물리적)에 따라 계산됩니다. 이 계산은 성능 서비스 수준 인스턴스별로 수행됩니다.
+
.. *논리적 용량*: 다음의 합계입니다.
+
*** 스토리지 어레이 데이터 효율성을 고려하기 전에, 복사본, 미러링된 복사본, 버전 및 클론과 같은 모든 인스턴스 및 유형의 고객 데이터를 저장하기 위한 계량화된 논리적 용량입니다.
*** 스냅샷 및 특정 클론의 메타데이터와 차등 데이터를 저장하는 데 사용되는 물리적 용량입니다.
*** 씩 프로비저닝된 물리적 용량.


.. *물리적 용량*: 다음의 합계입니다:
+
*** 복사본, 미러링된 복사본, 버전 및 클론과 같은 모든 인스턴스 및 유형의 고객 데이터를 저장하기 위한 스토리지 어레이 데이터 효율성 이후의 측정된 물리적 용량입니다.
*** 스냅샷의 메타데이터 및 차분 데이터를 저장하는 데 사용되는 물리적 용량.
*** 씩 프로비저닝된 물리적 용량.




* *객체 스토리지*: 사용량은 모든 노드에 걸쳐 모든 인스턴스와 고객 데이터 유형을 저장하는 데 사용된 측정된 물리적 용량의 양으로 계산됩니다. 이 계산은 구성된 정보 라이프사이클 관리(ILM) 정책을 기반으로 합니다.
* *Cloud Volumes ONTAP*: 소비된 용량은 모든 Cloud Volumes ONTAP 볼륨의 측정된 프로비저닝된 논리적 용량으로 계산됩니다.




[[burst-capacity]]
== 버스트 용량

NetApp Keystone 서비스를 사용하면 서비스 수준에서 약속된 용량 외에 추가 용량을 사용할 수 있습니다.  이를 버스트 용량 사용량이라고 합니다.

다음 사항에 유의하세요.

* 버스트 용량은 Keystone 협정에서 합의됩니다.  일반적으로 약정 용량보다 최대 20% 높게 설정되며, 약정 용량과 동일한 요금이 부과됩니다.
* 버스트 용량은 탄력적으로 소모될 수 있으며, 소모된 평균 용량에 대해 일일 요금이 청구됩니다.




[[billed-capacity]]
== 청구 용량

월별 청구서 = (약정 용량[TiB] * 약정 속도[$/TiB]) + (일일 평균 프로비저닝 버스트 용량[TiB] * 버스트 속도[$/TiB]).  월별 청구서에는 약정 용량을 기준으로 한 최소 요금이 포함되어 있습니다.

월별 청구서는 일일 평균 버스트 용량 소비량에 따라 최소 요금을 초과하여 다양합니다.
