---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: NetApp Keystone STaaS 서비스 버전 2에서 지원하는 스토리지 용량 유형에 대해 알아보세요. 
---
= Keystone 에서 지원되는 저장 용량
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 서비스는 여러 유형의 스토리지 용량을 지원합니다.  이러한 다양한 용량 용어를 이해하면 Keystone 사용할 때 도움이 될 수 있습니다.



== 논리적 용량

이는 고객이 Keystone 인프라에 저장한 데이터입니다.  모든 Keystone 용량은 논리적 용량을 나타냅니다.  예를 들어, 1TiB 파일이 Keystone 인프라에 저장되어 있는 경우 최소 1TiB의 용량을 구매해야 합니다.



== 약속된 용량

구독 기간 동안 매달 청구되는 최소 논리적 용량:

* 각 서비스 수준에 따라 용량이 결정됩니다.
* 계약 기간 중에 약속된 용량과 추가 서비스 수준을 추가할 수 있습니다.




=== 커밋된 용량 변경

구독 기간 동안 약정 용량을 변경할 수 있습니다.  하지만 다음과 같은 전제 조건이 있습니다.

* 특정 조건에 따라 약정된 용량을 줄일 수 있습니다.  자세한 내용은 다음을 참조하세요.link:../concepts/capacity-requirements.html["용량 감소"] .
* 구독을 추가로 12개월 기간으로 갱신하는 경우를 제외하고는 구독 만료일 90일 전부터는 약정 용량을 늘릴 수 없습니다.
* BlueXP 인터페이스나 Keystone Success Manager(KSM)를 통해 약정된 용량에 대한 변경을 요청할 수 있습니다.  변경 요청에 대한 정보는 다음을 참조하세요.link:../concepts/gssc.html["NetApp Keystone 지원"] .




== 소비 용량

소비 용량은 서비스에서 현재 소비되고 있는 용량(저장 용량의 TiB)을 말합니다.  다음의 합계입니다.

* 모든 인스턴스와 사용자 데이터 유형(복사본, 미러링된 사본, 버전 등)을 저장하는 데 사용되는 논리적 용량입니다.
* 원본 볼륨 크기의 10%가 넘는 복제 볼륨을 저장하는 데 사용되는 논리적 용량입니다.
* 스냅샷 복사본의 차등 데이터를 저장하는 데 사용되는 물리적 용량입니다.
* 할당된 물리적 용량.




== 버스트 용량

NetApp Keystone 서비스를 사용하면 서비스 수준에서 약속된 용량 외에 추가 용량을 사용할 수 있습니다.  이를 버스트 용량 사용량이라고 합니다.

다음 사항에 유의하세요.

* 버스트 용량은 Keystone 협정에서 합의됩니다.  일반적으로 약정 용량보다 최대 20% 높게 설정되며, 약정 용량과 동일한 요금이 부과됩니다.
* 버스트 용량은 탄력적으로 소모될 수 있으며, 소모된 평균 용량에 대해 일일 요금이 청구됩니다.




== 청구 용량

월별 청구서 = (약정 용량[TiB] * 약정 속도[$/TiB]) + (일일 평균 프로비저닝 버스트 용량[TiB] * 버스트 속도[$/TiB]).  월별 청구서에는 약정 용량을 기준으로 한 최소 요금이 포함되어 있습니다.

월별 청구서는 일일 평균 버스트 용량 소비량에 따라 최소 요금을 초과하여 다양합니다.
