---
sidebar: sidebar 
permalink: installation/asup-config.html 
keywords: ASUP, AutoSupport configuration 
summary: ONTAP 클러스터에서 보낸 일일 지원 번들에 Keystone 데이터를 통합하도록 AutoSupport 구성합니다. 
---
= Keystone 에 대한 AutoSupport 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AutoSupport 원격 측정 메커니즘을 사용하는 경우 Keystone AutoSupport 원격 측정 데이터를 기반으로 사용량을 계산합니다.  필요한 수준의 세분성을 달성하려면 ONTAP 클러스터에서 보낸 일일 지원 번들에 Keystone 데이터를 통합하도록 AutoSupport 구성해야 합니다.

.이 작업에 관하여
Keystone 데이터를 포함하도록 AutoSupport 구성하기 전에 다음 사항에 유의하세요.

* ONTAP CLI를 사용하여 AutoSupport 원격 측정 옵션을 편집합니다.  AutoSupport 서비스 및 시스템(클러스터) 관리자 역할 관리에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html["AutoSupport 관리 개요"^] 그리고 https://docs.netapp.com/us-en/ontap/system-admin/cluster-svm-administrators-concept.html["클러스터 및 SVM 관리자"^] .
* Keystone 의 정확한 데이터 수집을 보장하기 위해 일일 및 주간 AutoSupport 번들에 하위 시스템을 포함합니다.  AutoSupport 하위 시스템에 대한 정보는 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/system-admin/autosupport-subsystem-collection-reference.html["AutoSupport 하위 시스템은 무엇입니까?"^] .


.단계
. 시스템 관리자 사용자로서 SSH를 사용하여 Keystone ONTAP 클러스터에 로그인합니다.  자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-ssh-task.html["SSH를 사용하여 클러스터에 액세스합니다."^] .
. 로그 내용을 수정합니다.
+
** ONTAP 9.16.1 이상의 경우 다음 명령을 실행하여 일일 로그 내용을 수정하세요.
+
[source]
----
autosupport trigger modify -node * -autosupport-message management.log -basic-additional wafl,performance,snapshot,object_store_server,san,raid,snapmirror -troubleshooting-additional wafl
----
** 이전 ONTAP 버전의 경우 다음 명령을 실행하여 일일 로그 내용을 수정하세요.
+
[source]
----
autosupport trigger modify -node * -autosupport-message management.log -basic-additional wafl,performance,snapshot,platform,object_store_server,san,raid,snapmirror -troubleshooting-additional wafl
----
** 주간 로그 내용을 수정하려면 다음 명령을 실행하세요.
+
[source]
----
autosupport trigger modify -autosupport-message weekly -troubleshooting-additional wafl -node *
----
+
이 명령에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-trigger-modify.html["시스템 노드 자동 지원 트리거 수정"^] .




