---
sidebar: sidebar 
permalink: installation/install-itom-linux.html 
keywords: Linux installation, ITOM Collector installation 
summary: Linux 기반 시스템에 ITOM Collector 소프트웨어를 설치합니다. 
---
= Linux 시스템에 ITOM Collector 설치
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
스토리지 환경에서 메트릭 데이터를 수집하는 ITOM Collector를 설치하려면 몇 가지 단계를 완료하세요.  요구 사항에 따라 Windows나 Linux 시스템에 설치할 수 있습니다.


NOTE: Keystone 지원팀은 ITOM Collector 설치 파일을 다운로드할 수 있는 동적 링크를 제공하는데, 이 링크는 2시간 후에 만료됩니다.

Windows 시스템에 ITOM Collector를 설치하려면 다음을 참조하세요.link:../installation/install-itom-windows.html["Windows 시스템에 ITOM Collector 설치"] .

Linux 서버에 소프트웨어를 설치하려면 다음 단계를 따르세요.

.시작하기 전에
* Linux 설치 스크립트에 Bourne shell을 사용할 수 있는지 확인하세요.
* 설치하다 `vim-common` ITOM Collector 설치 파일에 필요한 *xxd* 바이너리를 얻기 위한 패키지입니다.
* 확인하십시오 `sudo package` 루트가 아닌 사용자로 ITOM Collector를 실행하려는 경우 설치됩니다.


.단계
. ITOM 수집기 설치 파일을 Linux 서버에 다운로드합니다.
. 서버에서 터미널을 열고 다음 명령을 실행하여 권한을 변경하고 바이너리를 실행 가능하게 만듭니다.
`# chmod +x <installer_file_name>.bin`
. ITOM 수집기 설치 파일을 시작하려면 다음 명령을 실행하세요.
`#./<installer_file_name>.bin`
. 설치 파일을 실행하면 다음 메시지가 표시됩니다.
+
.. 최종 사용자 라이선스 계약(EULA)에 동의합니다.
.. 설치를 위해 사용자 세부 정보를 입력하세요.
.. 설치 상위 디렉토리를 지정합니다.
.. 수집기 크기를 선택하세요.
.. 해당되는 경우, 대리인 세부 정보를 제공하세요.
+
각 프롬프트에 대해 기본 옵션이 표시됩니다.  특별한 요구 사항이 없다면 기본 옵션을 선택하는 것이 좋습니다.  기본 옵션을 선택하려면 *Enter* 키를 누르세요.  설치가 완료되면 ITOM Collector가 성공적으로 설치되었다는 메시지가 나타납니다.





[NOTE]
====
* ITOM Collector 설치 파일은 다음을 추가합니다. `/etc/sudoers` 서비스 재시작 및 메모리 덤프를 처리합니다.
* Linux 서버에 ITOM Collector를 설치하면 *ITOM*이라는 기본 사용자가 생성되어 루트 권한 없이 ITOM Collector를 실행합니다.  다른 사용자를 선택하거나 루트로 실행할 수 있지만 Linux 설치 스크립트에서 생성된 ITOM 사용자를 사용하는 것이 좋습니다.


====
.다음은 무엇인가요?
성공적으로 설치되면 Keystone 지원팀에 연락하여 ITOM 지원 포털을 통해 ITOM Collector가 성공적으로 설치되었는지 확인하세요.  검증 후, Keystone 지원팀은 ITOM 수집기를 원격으로 구성하고, 추가적인 장치 검색 및 모니터링 설정을 진행하며, 구성이 완료되면 확인 메시지를 보냅니다.  문의사항이나 추가 정보가 있으시면 keystone.services@netapp.com으로 연락해 주시기 바랍니다.
