---
sidebar: sidebar 
permalink: installation/security.html 
keywords: VMware, security, hardening, Keystone Collector 
summary: Keystone Collector에는 Keystone 시스템의 성능과 사용 지표를 모니터링하는 보안 기능이 포함되어 있으며, 보안이 강화된 구성을 사용하도록 구성되어 있습니다. 
---
= Keystone 콜렉터 보안
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone Collector에는 고객 데이터 보안을 위협하지 않으면 Keystone 시스템의 성능과 사용 측정 항목을 모니터링하는 보안 기능이 포함되어 있습니다.

Keystone Collector의 기능은 다음과 같은 보안 원칙에 따라 작동합니다.

* *개인정보 보호를 위한 설계*- Keystone Collector는 사용량 측정 및 성능 모니터링을 수행하기 위해 최소한의 데이터를 수집합니다. 자세한 내용은 다음을 참조하세요. link:data-collection.html["청구를 위해 수집된 데이터"^] .  그만큼link:configuration.html#limit-collection-of-private-data["개인 데이터 제거"] 민감한 정보를 마스크하고 보호하는 옵션이 기본적으로 활성화되어 있습니다.
* *최소 권한 액세스*- Keystone Collector는 스토리지 시스템을 모니터링하기 위해 최소한의 권한만 요구하며, 이를 통해 보안 위험을 최소화하고 데이터에 대한 의도치 않은 수정을 방지합니다.  이러한 접근 방식은 최소 권한의 원칙에 부합하며, 모니터링되는 환경의 전반적인 보안 태세를 강화합니다.
* *안전한 소프트웨어 개발 프레임워크*- Keystone 개발 주기 전반에 걸쳐 안전한 소프트웨어 개발 프레임워크를 사용하여 위험을 완화하고, 취약성을 줄이며, 잠재적 위협으로부터 시스템을 보호합니다.




== 보안 강화

기본적으로 Keystone Collector는 보안이 강화된 구성을 사용하도록 구성됩니다.  권장되는 보안 구성은 다음과 같습니다.

* Keystone Collector 가상 머신의 운영 체제:
+
** CIS Debian Linux 12 벤치마크 표준을 준수합니다.  Keystone Collector 관리 소프트웨어 외부에서 OS 구성을 변경하면 시스템 보안이 약화될 수 있습니다. 자세한 내용은 다음을 참조하세요. link:https://learn.cisecurity.org/benchmarks["CIS 벤치마크 가이드"^] .
** Keystone Collector의 자동 업데이트 기능을 통해 검증된 보안 패치를 자동으로 수신하여 설치합니다.  이 기능을 비활성화하면 패치되지 않은 취약한 소프트웨어가 설치될 수 있습니다.
** Keystone Collector에서 받은 업데이트를 인증합니다.  APT 저장소 검증을 비활성화하면 승인되지 않은 패치가 자동으로 설치되어 잠재적으로 취약점이 발생할 수 있습니다.


* Keystone Collector는 HTTPS 인증서를 자동으로 검증하여 연결 보안을 보장합니다.  이 기능을 비활성화하면 외부 엔드포인트 사칭 및 사용 데이터 유출이 발생할 수 있습니다.
* Keystone Collector 지원link:configuration.html#trust-a-custom-root-ca["맞춤형 신뢰할 수 있는 CA"] 인증.  기본적으로는 공개 루트 CA에서 인식한 서명된 인증서를 신뢰합니다.link:https://wiki.mozilla.org/CA["모질라 CA 인증 프로그램"^] .  Keystone Collector는 신뢰할 수 있는 CA를 추가로 활성화하여 이러한 인증서를 제시하는 엔드포인트에 대한 연결에 대해 HTTPS 인증서 유효성 검사를 활성화합니다.
* Keystone 수집기는 기본적으로 *개인 데이터 제거* 옵션을 활성화하여 민감한 정보를 마스크하고 보호합니다. 자세한 내용은 다음을 참조하세요. link:configuration.html#limit-collection-of-private-data["개인정보 수집 제한"^] .  이 옵션을 비활성화하면 추가 데이터가 Keystone 시스템으로 전송됩니다.  예를 들어, 볼륨 이름과 같이 민감한 정보로 간주될 수 있는 사용자가 입력한 정보가 포함될 수 있습니다.


*관련 정보*

* link:installation-overview.html["Keystone 컬렉터 개요"]
* link:vapp-prereqs.html["가상 인프라 요구 사항"]
* link:configuration.html["Keystone Collector 구성"]

