---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: NetApp Keystone STaaS 서비스의 이전 릴리스에서 발견된 문제는 이후 릴리스에서 수정되었습니다. 
---
= Keystone STaaS의 문제가 해결되었습니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 서비스의 이전 릴리스에서 발견된 문제는 이후 릴리스에서 수정되었습니다.

[cols="3*"]
|===
| 문제 설명 | 수정 후 | 릴리스에서 수정됨 


 a| 
Digital Advisor 대시보드에서 MetroCluster 구성으로 구성된 구독의 소비 추세 차트에서 버스트 임계값 선이 누락되어 잘못된 *버스트 한도 초과* 상태가 표시됩니다.
 a| 
결정된
 a| 
2025년 8월 28일



 a| 
*자산* 탭에서 StorageGRID 에 대한 자산은 표시되지 않습니다.
 a| 
결정된
 a| 
2025년 6월 19일



 a| 
Advanced Data-Protect 서비스 수준의 경우, *소비 추세* 탭에서 차트는 기본 사이트와 미러 사이트를 구분하여 보여줍니다.
 a| 
차트에는 더 이상 기본 사이트와 미러 사이트의 구분이 표시되지 않습니다.
 a| 
2025년 6월 19일



 a| 
Debian 패키지를 사용하여 설치된 기존 Keystone Collector가 Keystone Collector 관리 TUI를 통해 HTTP 프록시를 구성하거나 Unified Manager를 활성화하려고 하면 TUI가 응답하지 않습니다.
 a| 
결정된
 a| 
2025년 5월 19일



 a| 
공통 설정이 누락되어 StorageGRID 용 Keystone Collector가 올바르게 구성되지 않습니다.
 a| 
결정된
 a| 
2025년 5월 12일



 a| 
Keystone Collector는 9.11보다 낮은 버전을 실행하는 ONTAP 클러스터의 사용 데이터를 수집하지 못합니다.
 a| 
결정된
 a| 
2025년 4월 30일



 a| 
연결된 구독의 소비 값이 잘못된 음수를 표시하여 총 약정 사용량이 부정확하게 높게 표시됩니다.
 a| 
결정된
 a| 
2025년 4월 14일



 a| 
일부 구독의 서비스 수준에 대한 *소비 추세* 탭에서 과거 데이터를 볼 수 없습니다.
 a| 
결정된
 a| 
2025년 4월 14일



 a| 
Digital Advisor 대시보드의 *관심 목록*에서 * Keystone 구독* 옵션이 누락되었고, *보고서*에서 *구독 번호* 옵션이 누락되었습니다.
 a| 
결정된
 a| 
2025년 3월 19일



 a| 
Digital Advisor 대시보드에서 관심 목록을 만들거나 수정한 후, *관심 목록*에서 몇 개의 Keystone 구독이 누락되었습니다.
 a| 
결정된
 a| 
2025년 3월 19일



 a| 
동일한 추적 ID로 만료되어 갱신되었지만 서비스 수준이 다른 구독과 관련된 서비스 수준에 대한 *소비 추세* 탭에서 과거 데이터를 볼 수 없습니다.
 a| 
결정된
 a| 
2025년 3월 19일



 a| 
* Keystone 구독* 페이지의 *구독* 탭에서 10-12개 이상의 구독을 선택하면 구독에 대한 보고서를 생성할 수 없습니다.
 a| 
결정된
 a| 
2025년 1월 8일



 a| 
StorageGrid 구독의 경우 *볼륨 및 개체* 탭의 *볼륨 요약* 하위 탭이 로드되지 않습니다.
 a| 
결정된
 a| 
2024년 11월 21일



 a| 
*시작 날짜* 필드에서 날짜 범위를 선택하면 *소비 추세* 탭으로 이동하면 기본적으로 미래 날짜가 표시됩니다.
 a| 
결정된
 a| 
2024년 9월 4일



 a| 
AQoS 정책을 설정할 때 Keystone Collector 관리 TUI가 응답하지 않습니다.
 a| 
결정된
 a| 
2024년 8월 7일



 a| 
*용량 추세* 탭의 *용량 추세* 옵션에서 이전 달의 시작 날짜와 종료 날짜로 현재 날짜에 해당하는 날짜를 선택한 경우, 사용 차트는 지정된 하루 기간을 초과한 데이터를 표시합니다.
 a| 
이제 사용 차트에 지정된 하루 동안의 데이터가 올바르게 표시됩니다.
 a| 
2024년 6월 27일



 a| 
MetroCluster 구성으로 구성되지 않은 구독의 경우 *용량 추세* 탭에서 *CVO 기본* 및 *CVO 보조* 서비스 수준에 대한 과거 누적 버스트 데이터를 사용할 수 없습니다.
 a| 
결정된
 a| 
2024년 6월 21일



 a| 
AutoSupport 구독의 *볼륨 세부 정보* 탭에 나열된 개체 스토리지 소비 값이 잘못 표시되었습니다.
 a| 
이제 개체 저장소에 사용된 값이 올바르게 표시됩니다.
 a| 
2024년 6월 21일



 a| 
MetroCluster 구성으로 구성된 AutoSupport 구독의 *자산* 탭에서 클러스터 수준 정보를 볼 수 없습니다.
 a| 
결정된
 a| 
2024년 6월 21일



 a| 
*용량 추세* 탭에서 생성된 CSV 보고서의 *계정 이름* 열에 쉼표가 있는 계정 이름이 포함된 경우 CSV 보고서에서 Keystone 데이터가 잘못 배치됨 `(,)` .
 a| 
Keystone 데이터가 CSV 보고서에 올바르게 정렬되었습니다.
 a| 
2024년 5월 29일



 a| 
사용량이 약정 용량보다 낮은 경우에도 *용량 추세* 탭에서 누적된 버스트 사용량을 표시합니다.
 a| 
결정된
 a| 
2024년 5월 29일



 a| 
*용량 추세* 탭의 *현재 버스트* 인덱스 아이콘에 대한 도구 설명 텍스트가 잘못되었습니다.
 a| 
올바른 툴팁 텍스트 "_현재 소모되고 있는 버스트 용량입니다.  이것은 선택된 날짜 범위가 아닌 현재 청구 기간에 대한 내용입니다.
 a| 
2024년 3월 28일



 a| 
Keystone 데이터가 24시간 동안 제공되지 않으면 AutoSupport 구독에 대해 AQoS 비준수 볼륨 및 MetroCluster 파트너에 대한 정보를 사용할 수 없습니다.
 a| 
결정된
 a| 
2024년 3월 28일



 a| 
두 개의 서비스 수준이 하나의 서비스 수준에 대해서만 AQoS 규정을 충족하는 볼륨에 할당된 경우, *볼륨 요약* 및 *볼륨 세부 정보* 탭에 나열된 AQoS 비준수 볼륨 수가 가끔 일치하지 않습니다.
 a| 
결정된
 a| 
2024년 3월 28일



 a| 
AutoSupport 구독에 대한 *자산* 탭에는 정보가 없습니다.
 a| 
결정된
 a| 
2024년 3월 14일



 a| 
계층화와 개체 스토리지에 대한 요금제가 적용되는 환경에서 MetroCluster 와 FabricPool 모두 활성화된 경우 미러 볼륨(구성 요소와 FabricPool 볼륨 모두)에 대한 서비스 수준이 잘못 도출될 수 있습니다.
 a| 
미러 볼륨에 올바른 서비스 수준이 적용됩니다.
 a| 
2024년 2월 29일



 a| 
단일 서비스 수준이나 요금제가 있는 일부 구독의 경우, *볼륨* 탭 보고서의 CSV 출력에서 AQoS 준수 열이 누락되었습니다.
 a| 
규정 준수 열은 보고서에서 볼 수 있습니다.
 a| 
2024년 2월 29일



 a| 
일부 MetroCluster 환경에서는 *성능* 탭의 IOPS 밀도 차트에서 가끔씩 이상 현상이 감지되었습니다.  이는 서비스 수준에 대한 볼륨 매핑이 부정확하여 발생했습니다.
 a| 
차트가 올바르게 표시됩니다.
 a| 
2024년 2월 29일



 a| 
버스트 소비 기록에 대한 사용 표시기가 주황색으로 표시되었습니다.
 a| 
표시기는 빨간색으로 나타납니다.
 a| 
2023년 12월 13일



 a| 
용량 추세, 현재 사용량, 성능 탭의 날짜 범위와 데이터는 UTC 시간대로 변환되지 않았습니다.
 a| 
모든 탭의 쿼리 및 데이터에 대한 날짜 범위는 UTC 시간(서버 시간대)으로 표시됩니다.  각 날짜 필드에는 UTC 시간대도 표시됩니다.
 a| 
2023년 12월 13일



 a| 
탭과 다운로드한 CSV 보고서의 시작 날짜와 종료 날짜가 일치하지 않습니다.
 a| 
결정된.
 a| 
2023년 12월 13일

|===